"""Generate a 16x28 antialiased ASCII font. Requires Pillow only to regenerate."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf', 24)
out = ['/* Generated by scripts/generate_tft_font.py; see FONT_LICENSE.txt. */',
       'static const uint8_t smooth_font[95][448] = {']
for code in range(32, 127):
    img = Image.new('L', (16, 28))
    ImageDraw.Draw(img).text((0, 0), chr(code), font=font, fill=255)
    out.append('{' + ','.join(str(v) for v in img.getdata()) + '},')
out.append('};')
Path('Modules/TFT/Src/font_smooth.h').write_text('\n'.join(out) + '\n')
